# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2

initWorkingDir: &initWorkingDir
  type: shell
  name: Initialize Working Directory
  pwd: /
  command: |
    mkdir -p ~/go/src/${CIRCLE_PROJECT_USERNAME}/coredns
    sudo chown -R circleci ~/go
    mkdir -p ~/go/out/tests
    mkdir -p ~/go/out/logs
    mkdir -p /home/circleci/logs
    GOROOT=$(go env GOROOT)
    sudo rm -r $(go env GOROOT)
    sudo mkdir $GOROOT
    LATEST=$(curl -s https://golang.org/VERSION?m=text)
    curl https://dl.google.com/go/${LATEST}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/go/src/${CIRCLE_PROJECT_USERNAME}/coredns
    steps:
      - <<: *initWorkingDir
      - checkout
      - run:
          name: Generate Go modules
          command: go generate
      - run:
          name: Build CoreDNS Docker image
          command: |
            cd ~/go/src/${CIRCLE_PROJECT_USERNAME}/coredns
            make coredns SYSTEM="GOOS=linux" && \
            docker build -t $DOCKER_USER/coredns . && \
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/coredns

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
              branches:
                only:
                  - master