// generated by directives_generate.go; DO NOT EDIT

package dnsserver

// Directives are registered in the order they should be
// executed.
//
// Ordering is VERY important. Every plugin will
// feel the effects of all other plugin below
// (after) them during a request, but they must not
// care what plugin above them are doing.
var Directives = []string{
	"metadata",
	"cancel",
	"tls",
	"reload",
	"nsid",
	"bufsize",
	"root",
	"debug",
	"trace",
	"ready",
	"health",
	"pprof",
	"errors",
	"log",
	"local",
	"acl",
	"any",
	"chaos",
	"cache",
	"dnssec",
	"autopath",
	"minimal",
	"hosts",
	"file",
	"auto",
	"secondary",
	"vpnrouting",
	"redis",
	"loop",
	"forward",
	"whoami",
	"on",
	"sign",
}
